---
title: "Full data extraction table"
output:
  pdf_document: 
    keep_tex: yes
---

```{r echo=FALSE, include=FALSE}
#' load packages
library('tidyverse')
library('readr')
library('xlsx')
library('ggthemes')
library('mdthemes')
library('scales')
library('janitor')
library('forcats')
library('stringr')
library('countrycode')
library('bib2df')
library('conflicted')
library('Hmisc')
library('kableExtra')
library('ggwordcloud')

#resolve package function conflicts
conflict_prefer('filter', 'dplyr')
conflict_prefer('select', 'dplyr')
conflict_prefer('kable', 'knitr')
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(dev = 'jpeg')
knitr::opts_chunk$set(fig.width = 8, fig.height = 6)
knitr::opts_chunk$set(message = FALSE)


#create a folder for storing the manuscript figures

if(!dir.exists('../figs_manuscript'))
    {
    dir.create('../figs_manuscript', 
               showWarnings = FALSE)
    }

#save figures in this folder
save_fig_here <- '../figs_manuscript'

save_thesis_fig_here <- "C:/Users/JAMESAZAM/Dropbox/My Academic Repository/_SACEMA/Academic/_PhD/__PhD_Thesis/_Thesis_LaTeX/figs/chapter_3"
```


```{r}
# Load the cleaned data 
long_data <- read_rds('../data/final_data/cleaned_data/review_data_long_cleaned.rds')

#The cleaned data without citations
compact_data_init <- read_rds('../data/final_data/cleaned_data/review_data_compact_cleaned.rds')


#a vector of shorter replacements for the original parametrization descriptions
parametrization_str_replacements <- c('values_from_literature' = 'literature', 
                  'values_from_guess_and_expert_opion' = 'expert_opinion', 
                  'values_fitted_to_ts' = 'fitted',
                  ' ' = ' and ' #replace space with 'and' to make it more readable
                  )

#a vector of shorter replacements for the original validation descriptions
validation_str_replacements <- c('compared_with_data' = 'data',
                                 'compared_with_other_model_output' = 'another_model',
                                 'model_not_validated' = 'none',
                                 ' ' = '_and_'
                                 )

# The data with citations 
compact_data_with_citation_keys_init <- read_rds(normalizePath('../data/final_data/cleaned_data/compact_data_with_citation_keys_cleaned.rds')) 

compact_data_with_citation_keys <- compact_data_with_citation_keys_init %>% 
    mutate(vax_modelled = ifelse(str_detect(intervention_modelled, 'vaccination'), 
                               'yes', 
                               'no')
         ) %>% 
  mutate(intervention_type = case_when(
    vax_modelled == 'no' & vax_modelled_with_non_vax == 'no' ~ 'no_vax', #Vaccination was not modelled
    vax_modelled == 'yes' & vax_modelled_with_non_vax == 'no' ~ 'vax_combination_with_others', #when vax was modelled but not for comparison as a single intervention
    vax_modelled == 'yes' & vax_modelled_with_non_vax == 'yes' ~ 'vax_single', #when vax was modelled as a single intervention
  )) %>% 
  mutate(publication_year = as.numeric(publication_year), 
         author_in_country_studied = as.character(author_in_country_studied)) %>% 
  arrange(publication_year) %>%
  mutate(
    author_affiliation_type = str_replace_all(author_affiliation_type, ' ', ' + '),
    author_in_country_studied = if_else(author_in_country_studied == 'NA', 'not_applicable',
                                        author_in_country_studied
                                        )
    ) %>% 
  mutate(year_aggreg = as.numeric(ifelse(publication_year < 2006, #An approach to aggregate the years before 2006 into one group because of the low number of papers
                                         2005, 
                                         publication_year
                                         )
                                  ), 
         collab_type = as_factor(if_else(author_affiliation_type == 'academic_institutions', 
                                         'purely_academic', 
                                         'mixed')
                                 )
         )

#replace the original descriptions of parametrization and validation with shorter strings
compact_data_with_citation_keys <- compact_data_with_citation_keys %>% 
  mutate(parametrization = str_replace_all(parametrization, 
                                           parametrization_str_replacements
                                           )
         ) %>% 
  mutate(validation = str_replace_all(validation, 
                                      validation_str_replacements
                                      )
         ) %>% 
  mutate(model_structure = str_replace(model_structure, 'deterministic stochastic', 'both'))
  

#Rearrange the columns
compact_data_with_citation_keys <- compact_data_with_citation_keys %>% 
  relocate(c(title, bibtexkey), .before = publication_year) %>% 
  relocate(publication_year, .before = bibtexkey) %>% 
  relocate(c(x0_reviewer, category, author:language), 
           .after = collab_type
           )
```

```{r}
final_citation_table <- compact_data_with_citation_keys %>% 
    relocate(c('doi', 'year', 'bibtexkey'), .after = title) %>% 
    select(-c(year_aggreg, x0_reviewer, category, 
              number, pages, journal, publisher, 
              volume, language, month, publication_type, 
              modelling_timing, intervention_type, collab_type,
              author, paper_doi,year
              )
           ) %>% 
    arrange(desc(publication_year))

knitr::kable(final_citation_table, 
                  format = "latex", 
             booktabs = TRUE,
                  caption = 'Full details of included studies and data extracted.'
                  ) %>%
  kable_styling(latex_options =c('striped', 'scale_down', 'hold_position'))

```
